#!/bin/bash

# gpg setup
gpgconf --launch dirmngr
gpg --keyserver keys.openpgp.org --recv 41AF08ED872634EB27A728062DCB1FDB966C8F17
export GPG_TTY=$(tty)

# zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/spaceship-prompt/spaceship-prompt.git ~/.oh-my-zsh/custom/themes/spaceship-prompt --depth=1
ln -s ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme
git clone https://github.com/mashaal/wild-cherry.git ~/.oh-my-zsh/custom/themes/wild-cherry --depth=1
ln -s ~/.oh-my-zsh/custom/themes/wild-cherry/zsh/wild-cherry.zsh-theme ~/.oh-my-zsh/custom/themes/wild-cherry.zsh-theme

if [ $SPIN ]; then
  DOTFILES=~/dotfiles
else
  DOTFILES=~/.dotfiles
fi

for i in $DOTFILES/conf/*; do
  echo "Installing $(basename $i)..."
  rm -rf ~/.$(basename $i)
  ln -s $i ~/.$(basename $i)
done

zsh
